version: '3.8'

services:
  stream-24-7:
    build: .
    container_name: amda_stream_24_7
    restart: always
    environment:
      - YOUTUBE_URL=rtmp://a.rtmp.youtube.com/live2
      - YOUTUBE_STREAM_KEY=${YOUTUBE_STREAM_KEY}
      - TIKTOK_URL=rtmp://live-push.tiktok.com/live
      - TIKTOK_STREAM_KEY=${TIKTOK_STREAM_KEY:-}
    volumes:
      - ./media:/home/stream/media:ro
      - ./logs:/var/log/livestream
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
